function addLayer(){const [w,h]=dimsForMode(),layers=getLayers();layers.splice(getActiveLayerIndex()+1,0,makeLayer('Layer '+(layers.length+1),w,h));setActiveLayerIndex(getActiveLayerIndex()+1);renderLayers();refreshAll();markChanged('レイヤ追加')}
function duplicateLayer(){const layers=getLayers(),src=layers[getActiveLayerIndex()],[w,h]=dimsForMode(),l=makeLayer(src.name+' copy',w,h);l.visible=src.visible;l.opacity=src.opacity;l.ctx.drawImage(src.canvas,0,0);layers.splice(getActiveLayerIndex()+1,0,l);setActiveLayerIndex(getActiveLayerIndex()+1);renderLayers();refreshAll();markChanged('レイヤ複製')}
function deleteLayer(){const layers=getLayers();if(layers.length<=1)return alert('最後のレイヤは削除できません');layers.splice(getActiveLayerIndex(),1);setActiveLayerIndex(clamp(getActiveLayerIndex(),0,layers.length-1));renderLayers();refreshAll();markChanged('レイヤ削除')}
function moveLayer(dir){const layers=getLayers(),i=getActiveLayerIndex(),j=clamp(i+dir,0,layers.length-1);if(i===j)return;[layers[i],layers[j]]=[layers[j],layers[i]];setActiveLayerIndex(j);renderLayers();refreshAll()}
function mergeDown(){const layers=getLayers(),i=getActiveLayerIndex();if(i<=0)return;const top=layers[i],bot=layers[i-1];bot.ctx.save();bot.ctx.globalAlpha=top.opacity;bot.ctx.drawImage(top.canvas,0,0);bot.ctx.restore();layers.splice(i,1);setActiveLayerIndex(i-1);renderLayers();refreshAll();markChanged('レイヤ統合')}
function renderLayers(){const root=$('#layerList'),layers=getLayers(),active=getActiveLayerIndex();root.innerHTML='';layers.slice().reverse().forEach((l,ri)=>{const i=layers.length-1-ri,row=document.createElement('div');row.className='layer-item'+(i===active?' active':'');row.onclick=e=>{if(e.target.matches('input,button'))return;setActiveLayerIndex(i);clearSelection();renderLayers()};const eye=document.createElement('button');eye.className='eye-btn';eye.textContent=l.visible?'◉':'○';eye.onclick=e=>{e.stopPropagation();l.visible=!l.visible;renderLayers();refreshAll()};const name=document.createElement('input');name.type='text';name.value=l.name;name.oninput=e=>{l.name=e.target.value};const ow=document.createElement('div');ow.className='opacity-wrap';const range=document.createElement('input');range.type='range';range.min=0;range.max=100;range.value=Math.round(l.opacity*100);range.addEventListener('pointerdown',e=>{e.stopPropagation()});range.addEventListener('click',e=>e.stopPropagation());range.addEventListener('input',e=>{e.stopPropagation();l.opacity=+e.target.value/100;val.textContent=e.target.value+'%';refreshVisuals()});range.addEventListener('change',()=>markChanged('レイヤ透明度'));const val=document.createElement('span');val.className='opacity-value';val.textContent=Math.round(l.opacity*100)+'%';ow.append(range,val);row.append(eye,name,ow);root.appendChild(row)});updateLayerContext()}
function updateLayerContext(){let t='Skin';if(state.mode==='model')t=`3D Model / Frame ${state.model.frame+1}`;if(state.mode==='item')t=`Item / Frame ${state.item.frame+1}`;if(state.mode==='block')t=`Block ${state.block.face} / Frame ${state.block.frame+1}`;$('#layerContext').textContent=t}

function setupViewport(el,view,update){let mode=null,sx=0,sy=0,rx=0,ry=0,px=0,py=0;el.addEventListener('contextmenu',e=>e.preventDefault());el.addEventListener('pointerdown',e=>{if(e.button===2)mode='rotate';else if(e.button===1)mode='pan';else return;e.preventDefault();sx=e.clientX;sy=e.clientY;rx=view.rx;ry=view.ry;px=view.panX;py=view.panY;el.setPointerCapture?.(e.pointerId)});el.addEventListener('pointermove',e=>{if(mode==='rotate'){view.ry=ry+(e.clientX-sx)*.45;view.rx=clamp(rx-(e.clientY-sy)*.45,-89,89);update()}else if(mode==='pan'){view.panX=px+(e.clientX-sx);view.panY=py+(e.clientY-sy);update()}});el.addEventListener('pointerup',()=>mode=null);el.addEventListener('pointercancel',()=>mode=null);el.addEventListener('wheel',e=>{e.preventDefault();view.zoom=clamp(view.zoom*(e.deltaY>0?.9:1.1),.25,4);update()},{passive:false})}

function refreshVisuals(){if(state.mode==='skin')refreshSkin();if(state.mode==='model')refreshModel();if(state.mode==='item')refreshItem();if(state.mode==='block')refreshBlock();}
function refreshAll(){refreshVisuals();renderLayers();}
function markChanged(msg){setStatus(msg);$('#saveState').textContent='編集中';scheduleAutosave()}
function setStatus(msg){$('#statusText').textContent=msg}
let autosaveTimer=null;function scheduleAutosave(){clearTimeout(autosaveTimer);autosaveTimer=setTimeout(()=>{try{if(state.mode==='skin')localStorage.setItem('wcs_v04_skin',JSON.stringify(serializeSkinProject()));$('#saveState').textContent='自動保存済'}catch(e){}},900)}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function canvasToBlob(canvas){return new Promise(resolve=>canvas.toBlob(resolve,'image/png'))}
function dataURLToImage(url){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=url})}
function fileToImage(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>dataURLToImage(r.result).then(res,rej);r.onerror=rej;r.readAsDataURL(file)})}
function loadImageIntoLayer(img,layer,w,h,sx=0,sy=0,sw=img.width,sh=img.height){layer.ctx.clearRect(0,0,w,h);layer.ctx.drawImage(img,sx,sy,sw,sh,0,0,w,h)}

function serializeSkinProject(){return {type:'WCS-SKIN',version:4,armModel:state.skin.armModel,layers:state.skin.layers.map(l=>({name:l.name,visible:l.visible,opacity:l.opacity,png:l.canvas.toDataURL()}))}}
async function saveSkinProject(){downloadBlob(new Blob([JSON.stringify(serializeSkinProject(),null,2)],{type:'application/json'}),'skin.wcsproj.json')}
async function loadSkinProject(file){const obj=JSON.parse(await file.text());if(obj.type!=='WCS-SKIN')throw new Error('WCS Skin projectではありません');state.skin.armModel=obj.armModel||'classic';state.skin.layers=[];for(const o of obj.layers){const l=makeLayer(o.name,64,64);l.visible=o.visible;l.opacity=o.opacity;const img=await dataURLToImage(o.png);l.ctx.drawImage(img,0,0);state.skin.layers.push(l)}state.skin.activeLayer=0;$('#armModel').value=state.skin.armModel;buildSkinModel();renderLayers();markChanged('Skin Project読込')}
async function importSkinPNG(file,compare=false){const img=await fileToImage(file);if(img.width!==64||img.height!==64)return alert('64×64 PNGを選んでください');if(compare){const c=makeCanvas(64,64);c.getContext('2d').drawImage(img,0,0);state.skin.compare=c;refreshSkin();return}pushUndo();const l=state.skin.layers[state.skin.activeLayer];l.ctx.clearRect(0,0,64,64);l.ctx.drawImage(img,0,0);refreshSkin();markChanged('スキンPNG読込')}
async function exportSkin(){downloadBlob(await canvasToBlob(skinComposite(false)),'minecraft_skin.png')}
