function hexToRgb(h){h=h.replace('#','');if(h.length===3)h=h.split('').map(x=>x+x).join('');return [parseInt(h.slice(0,2),16)||0,parseInt(h.slice(2,4),16)||0,parseInt(h.slice(4,6),16)||0]}
function rgbToHex(r,g,b){return '#'+[r,g,b].map(v=>clamp(Math.round(v),0,255).toString(16).padStart(2,'0')).join('')}
function rgbToHsv(r,g,b){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=0;if(d){if(max===r)h=((g-b)/d)%6;else if(max===g)h=(b-r)/d+2;else h=(r-g)/d+4;h*=60;if(h<0)h+=360;}return {h,s:max?d/max:0,v:max}}
function hsvToRgb(h,s,v){const c=v*s,x=c*(1-Math.abs((h/60)%2-1)),m=v-c;let r=0,g=0,b=0;if(h<60)[r,g,b]=[c,x,0];else if(h<120)[r,g,b]=[x,c,0];else if(h<180)[r,g,b]=[0,c,x];else if(h<240)[r,g,b]=[0,x,c];else if(h<300)[r,g,b]=[x,0,c];else[r,g,b]=[c,0,x];return [(r+m)*255,(g+m)*255,(b+m)*255]}
function setColor(hex,remember=true){if(!/^#[0-9a-fA-F]{6}$/.test(hex))return;state.color=hex.toLowerCase();state.hsv=rgbToHsv(...hexToRgb(hex));$('#colorHex').value=state.color;$('#colorPreview').style.background=state.color;if(remember){state.recentColors=[state.color,...state.recentColors.filter(x=>x!==state.color)].slice(0,10);renderRecentColors();}drawColorPad();}
function drawColorPad(){const sv=$('#svPad'),sx=sv.getContext('2d'),w=sv.width,h=sv.height;const hueHex=rgbToHex(...hsvToRgb(state.hsv.h,1,1));sx.fillStyle=hueHex;sx.fillRect(0,0,w,h);let g=sx.createLinearGradient(0,0,w,0);g.addColorStop(0,'#fff');g.addColorStop(1,'rgba(255,255,255,0)');sx.fillStyle=g;sx.fillRect(0,0,w,h);g=sx.createLinearGradient(0,0,0,h);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(1,'#000');sx.fillStyle=g;sx.fillRect(0,0,w,h);const cx=state.hsv.s*w,cy=(1-state.hsv.v)*h;sx.strokeStyle='#fff';sx.lineWidth=2;sx.beginPath();sx.arc(cx,cy,6,0,Math.PI*2);sx.stroke();sx.strokeStyle='#000';sx.lineWidth=1;sx.beginPath();sx.arc(cx,cy,7,0,Math.PI*2);sx.stroke();const hc=$('#huePad'),hx=hc.getContext('2d'),hh=hc.height;const hg=hx.createLinearGradient(0,0,0,hh);for(let i=0;i<=6;i++)hg.addColorStop(i/6,`hsl(${i*60},100%,50%)`);hx.fillStyle=hg;hx.fillRect(0,0,hc.width,hh);const y=(state.hsv.h/360)*hh;hx.fillStyle='#fff';hx.fillRect(0,clamp(y-1,0,hh-2),hc.width,2);}
function bindColorPad(){const bind=(canvas,kind)=>{let down=false;const move=e=>{const r=canvas.getBoundingClientRect();if(kind==='sv'){state.hsv.s=clamp((e.clientX-r.left)/r.width,0,1);state.hsv.v=1-clamp((e.clientY-r.top)/r.height,0,1)}else state.hsv.h=clamp((e.clientY-r.top)/r.height,0,.9999)*360;state.color=rgbToHex(...hsvToRgb(state.hsv.h,state.hsv.s,state.hsv.v));$('#colorHex').value=state.color;$('#colorPreview').style.background=state.color;drawColorPad()};canvas.addEventListener('pointerdown',e=>{down=true;canvas.setPointerCapture?.(e.pointerId);move(e)});canvas.addEventListener('pointermove',e=>down&&move(e));canvas.addEventListener('pointerup',()=>{down=false;setColor(state.color,true)});canvas.addEventListener('pointercancel',()=>down=false)};bind($('#svPad'),'sv');bind($('#huePad'),'hue');}
function renderRecentColors(){const root=$('#recentColors');root.innerHTML='';for(const c of state.recentColors){const b=document.createElement('button');b.className='recent-color';b.style.background=c;b.title=c;b.onclick=()=>setColor(c);root.appendChild(b)}}

function tonedColor(hex,x,y){const [r,g,b]=hexToRgb(hex);if(!state.autoTone)return [r,g,b];const n=((x*73856093)^(y*19349663))>>>0,t=((n%2001)/1000-1)*state.autoToneStrength;return [r+t,g+t,b+t].map(v=>clamp(Math.round(v),0,255))}
function brushOffsets(size,shape){const out=[],rad=(size-1)/2;for(let yy=0;yy<size;yy++)for(let xx=0;xx<size;xx++){const dx=xx-rad,dy=yy-rad;let ok=true;if(shape==='circle')ok=dx*dx+dy*dy<=(size/2)*(size/2)+.2;if(shape==='diamond')ok=Math.abs(dx)+Math.abs(dy)<=Math.ceil(size/2)-.25;if(shape==='cross')ok=Math.abs(dx)<.55||Math.abs(dy)<.55;if(ok)out.push([Math.round(dx),Math.round(dy)])}return [...new Map(out.map(v=>[v.join(','),v])).values()]}
function putPixel(ctx,x,y,w,h,erase=false){if(x<0||y<0||x>=w||y>=h)return;if(state.alphaLock&&!erase&&ctx.getImageData(x,y,1,1).data[3]===0)return;if(erase){ctx.clearRect(x,y,1,1);return}const [r,g,b]=tonedColor(state.color,x,y);ctx.fillStyle=`rgb(${r},${g},${b})`;ctx.fillRect(x,y,1,1)}
function sampleAt(ctx,x,y){const d=ctx.getImageData(x,y,1,1).data;if(d[3])setColor(rgbToHex(d[0],d[1],d[2]))}
function floodFill(ctx,sx,sy,erase=false){const w=ctx.canvas.width,h=ctx.canvas.height;if(sx<0||sy<0||sx>=w||sy>=h)return;const img=ctx.getImageData(0,0,w,h),d=img.data,i0=(sy*w+sx)*4,target=[d[i0],d[i0+1],d[i0+2],d[i0+3]],rep=erase?[0,0,0,0]:[...tonedColor(state.color,sx,sy),255];if(target.every((v,i)=>v===rep[i]))return;const q=[[sx,sy]],seen=new Uint8Array(w*h);while(q.length){const [x,y]=q.pop(),idx=y*w+x;if(seen[idx])continue;seen[idx]=1;const i=idx*4;if(d[i]!==target[0]||d[i+1]!==target[1]||d[i+2]!==target[2]||d[i+3]!==target[3])continue;d[i]=rep[0];d[i+1]=rep[1];d[i+2]=rep[2];d[i+3]=rep[3];if(x>0)q.push([x-1,y]);if(x<w-1)q.push([x+1,y]);if(y>0)q.push([x,y-1]);if(y<h-1)q.push([x,y+1]);}ctx.putImageData(img,0,0)}

function snapshot(){const layers=getLayers();return {mode:state.mode,face:state.block.face,frame:state.mode==='skin'?0:(state.mode==='model'?state.model.frame:state.mode==='item'?state.item.frame:state.block.frame),layers:layers.map(l=>({name:l.name,visible:l.visible,opacity:l.opacity,data:l.ctx.getImageData(0,0,l.canvas.width,l.canvas.height)})),active:getActiveLayerIndex()}}
function pushUndo(){state.undo.push(snapshot());if(state.undo.length>state.maxHistory)state.undo.shift();state.redo=[];updateUndoButtons()}
function restoreSnapshot(s){if(s.mode!==state.mode){setStatus('Undo履歴はページごとにリセットされます');return}const layers=getLayers();layers.length=0;for(const o of s.layers){const l=makeLayer(o.name,o.data.width,o.data.height);l.visible=o.visible;l.opacity=o.opacity;l.ctx.putImageData(o.data,0,0);layers.push(l)}setActiveLayerIndex(clamp(s.active,0,layers.length-1));refreshAll();renderLayers()}
function undo(){if(!state.undo.length)return;state.redo.push(snapshot());restoreSnapshot(state.undo.pop());updateUndoButtons()}
function redo(){if(!state.redo.length)return;state.undo.push(snapshot());restoreSnapshot(state.redo.pop());updateUndoButtons()}
function updateUndoButtons(){$('#undoBtn').disabled=!state.undo.length;$('#redoBtn').disabled=!state.redo.length}
function resetHistory(){state.undo=[];state.redo=[];updateUndoButtons()}
