function recreateFrameSize(frame,newSize){const nf=makeFrame(newSize,newSize);const src=compositeLayers(frame.layers,frame.layers[0].canvas.width,frame.layers[0].canvas.height);nf.layers[0].ctx.drawImage(src,0,0,src.width,src.height,0,0,newSize,newSize);return nf}
function changeItemSize(size){size=+size;if(size===state.item.size)return;if(!confirm(`Itemを ${size}×${size} に変更しますか？ 現在の画像はリサイズされます。`)){ $('#itemSize').value=state.item.size;return}state.item.frames=state.item.frames.map(f=>recreateFrameSize(f,size));state.item.size=size;state.item.frame=0;state.item.previewFrame=0;resizePixelCanvas($('#itemCanvas'),size);resizePixelCanvas($('#itemPreviewCanvas'),size);refreshItem();renderLayers();resetHistory()}
function changeBlockSize(size){size=+size;if(size===state.block.size)return;if(!confirm(`Blockを ${size}×${size} に変更しますか？ 全6面をリサイズします。`)){ $('#blockSize').value=state.block.size;return}for(const face of Object.keys(state.block.faces))state.block.faces[face].frames=state.block.faces[face].frames.map(f=>recreateFrameSize(f,size));state.block.size=size;state.block.frame=0;state.block.previewFrame=0;resizePixelCanvas($('#blockCanvas'),size);buildBlockCube();refreshBlock();renderLayers();resetHistory()}
function resizePixelCanvas(c,size){c.width=size;c.height=size}
function refreshItem(){const fi=state.item.frame,comp=itemComposite(fi),c=$('#itemCanvas'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.drawImage(comp,0,0,c.width,c.height);const pi=state.item.playing?state.item.previewFrame:state.item.frame,pc=$('#itemPreviewCanvas'),px=pc.getContext('2d');px.clearRect(0,0,pc.width,pc.height);px.drawImage(itemComposite(pi),0,0,pc.width,pc.height)}
function refreshBlock(){const comp=blockComposite(state.block.face,state.block.frame),c=$('#blockCanvas'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.drawImage(comp,0,0,c.width,c.height);for(const face of Object.keys(state.block.faces)){const cv=$(`#blockCube canvas[data-face="${face}"]`);if(!cv)continue;const fi=state.block.playing?Math.min(state.block.previewFrame,state.block.faces[face].frames.length-1):Math.min(state.block.frame,state.block.faces[face].frames.length-1),cx=cv.getContext('2d');cx.clearRect(0,0,cv.width,cv.height);cx.drawImage(blockComposite(face,fi),0,0,cv.width,cv.height)}}
function bindPixelCanvas(canvas,kind){let down=false;canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;down=true;pushUndo();paintPixel(e,canvas,kind)});canvas.addEventListener('pointermove',e=>down&&paintPixel(e,canvas,kind));canvas.addEventListener('pointerup',()=>{down=false;markChanged(kind+'編集')});canvas.addEventListener('pointercancel',()=>down=false)}
function paintPixel(e,canvas,kind){const r=canvas.getBoundingClientRect(),size=kind==='item'?state.item.size:state.block.size,x=clamp(Math.floor((e.clientX-r.left)/r.width*size),0,size-1),y=clamp(Math.floor((e.clientY-r.top)/r.height*size),0,size-1),f=kind==='item'?state.item.frames[state.item.frame]:state.block.faces[state.block.face].frames[state.block.frame],l=f.layers[f.activeLayer];if(state.tool==='eyedropper'||e.altKey){sampleAt(l.ctx,x,y);return}if(state.tool==='fill'){floodFill(l.ctx,x,y,e.shiftKey);kind==='item'?refreshItem():refreshBlock();return}const erase=state.tool==='eraser'||e.shiftKey;for(const [dx,dy] of brushOffsets(state.brushSize,state.brushShape))putPixel(l.ctx,x+dx,y+dy,size,size,erase);kind==='item'?refreshItem():refreshBlock()}
function addFrame(kind,duplicate=false){let doc,frames,size;if(kind==='model'){doc=state.model;frames=doc.frames;size=[doc.w,doc.h]}else if(kind==='item'){doc=state.item;frames=doc.frames;size=[doc.size,doc.size]}else{doc=state.block;frames=doc.faces[doc.face].frames;size=[doc.size,doc.size]}const src=frames[doc.frame],nf={layers:[],activeLayer:src.activeLayer};for(const l of src.layers){const nl=makeLayer(l.name,size[0],size[1]);nl.visible=l.visible;nl.opacity=l.opacity;if(duplicate)nl.ctx.drawImage(l.canvas,0,0);nf.layers.push(nl)}frames.splice(doc.frame+1,0,nf);doc.frame++;doc.previewFrame=doc.frame;renderLayers();refreshAll();updateFrameLabels();markChanged('Frame追加')}
function delFrame(kind){let doc,frames;if(kind==='model'){doc=state.model;frames=doc.frames}else if(kind==='item'){doc=state.item;frames=doc.frames}else{doc=state.block;frames=doc.faces[doc.face].frames}if(frames.length<=1)return;frames.splice(doc.frame,1);doc.frame=clamp(doc.frame,0,frames.length-1);doc.previewFrame=doc.frame;renderLayers();refreshAll();updateFrameLabels()}
function stepFrame(kind,dir){clearSelection();let doc,frames;if(kind==='model'){doc=state.model;frames=doc.frames}else if(kind==='item'){doc=state.item;frames=doc.frames}else{doc=state.block;frames=doc.faces[doc.face].frames}doc.frame=(doc.frame+dir+frames.length)%frames.length;doc.previewFrame=doc.frame;renderLayers();refreshAll();updateFrameLabels();resetHistory()}
function togglePlay(kind){const doc=kind==='model'?state.model:kind==='item'?state.item:state.block;const frames=kind==='block'?doc.faces[doc.face].frames:doc.frames;doc.playing=!doc.playing;const btn=$(`#${kind}PlayBtn`);btn.textContent=doc.playing?'⏸ 停止':'▶ 再生';clearInterval(doc.timer);if(doc.playing){doc.previewFrame=doc.frame;doc.timer=setInterval(()=>{doc.previewFrame=(doc.previewFrame+1)%frames.length;if(kind==='model')refreshModel();else if(kind==='item')refreshItem();else refreshBlock()},1000/clamp(doc.fps,1,20))}else{doc.previewFrame=doc.frame;refreshAll()}}
function updateFrameLabels(){$('#modelFrameLabel').textContent=`Frame ${state.model.frame+1} / ${state.model.frames.length}`;$('#itemFrameLabel').textContent=`Frame ${state.item.frame+1} / ${state.item.frames.length}`;const bf=state.block.faces[state.block.face].frames;$('#blockFrameLabel').textContent=`Frame ${state.block.frame+1} / ${bf.length}`;updateLayerContext()}
async function importAnimatedPNG(file,kind){const img=await fileToImage(file),size=kind==='item'?state.item.size:state.block.size;if(img.width!==size||img.height%size!==0)return alert(`幅 ${size}px、高さは ${size}px の倍数のPNGを選んでください`);const frames=[];for(let i=0;i<img.height/size;i++){const f=makeFrame(size,size);f.layers[0].ctx.drawImage(img,0,i*size,size,size,0,0,size,size);frames.push(f)}if(kind==='item'){state.item.frames=frames;state.item.frame=0;state.item.previewFrame=0}else{state.block.faces[state.block.face].frames=frames;state.block.frame=0;state.block.previewFrame=0}refreshAll();renderLayers();updateFrameLabels();markChanged(`${kind} PNG読込`)}
async function exportAnimatedPNG(kind){const doc=kind==='item'?state.item:state.block,frames=kind==='item'?doc.frames:doc.faces[doc.face].frames,size=doc.size,out=makeCanvas(size,size*frames.length),x=out.getContext('2d');frames.forEach((f,i)=>x.drawImage(compositeLayers(f.layers,size,size),0,i*size));downloadBlob(await canvasToBlob(out),kind==='item'?'item_texture.png':`block_${doc.face}.png`)}
function newItem(){state.item.frames=[makeFrame(state.item.size,state.item.size)];state.item.frame=0;state.item.previewFrame=0;refreshItem();renderLayers();updateFrameLabels();resetHistory()}
function newBlock(){for(const f of Object.keys(state.block.faces))state.block.faces[f].frames=[makeFrame(state.block.size,state.block.size)];state.block.frame=0;state.block.previewFrame=0;refreshBlock();renderLayers();updateFrameLabels();resetHistory()}
function initBlockTabs(){const root=$('#blockFaceTabs');root.innerHTML='';for(const face of Object.keys(state.block.faces)){const b=document.createElement('button');b.textContent=face;b.classList.toggle('active',face===state.block.face);b.onclick=()=>{clearSelection();state.block.face=face;state.block.frame=0;state.block.previewFrame=0;$$('#blockFaceTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');refreshBlock();renderLayers();updateFrameLabels();resetHistory()};root.appendChild(b)}}
function buildBlockCube(){const root=$('#blockCube');root.innerHTML='';const T=160;for(const face of ['front','back','left','right','top','bottom']){const c=makeCanvas(state.block.size,state.block.size);c.dataset.face=face;c.style.transform=({front:`translateZ(${T/2}px)`,back:`rotateY(180deg) translateZ(${T/2}px)`,left:`rotateY(-90deg) translateZ(${T/2}px)`,right:`rotateY(90deg) translateZ(${T/2}px)`,top:`rotateX(90deg) translateZ(${T/2}px)`,bottom:`rotateX(-90deg) translateZ(${T/2}px)`})[face];root.appendChild(c)}refreshBlock()}
