function bindUI(){
 $$('.mode-tab').forEach(b=>b.onclick=()=>switchMode(b.dataset.mode));
 $$('.tool').forEach(b=>b.onclick=()=>{$$('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.tool=b.dataset.tool;if(state.tool==='replace')setStatus('色置換：新しい色を選び、変えたい色をクリック');else if(state.tool==='select')setStatus('選択：左ドラッグで矩形範囲を選択')});
 $('#brushSize').oninput=e=>{state.brushSize=+e.target.value;$('#brushSizeLabel').textContent=e.target.value+' px'};$$('.brush-shape').forEach(b=>b.onclick=()=>{$$('.brush-shape').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.brushShape=b.dataset.shape});
 $('#autoTone').onchange=e=>state.autoTone=e.target.checked;$('#autoToneStrength').onchange=e=>state.autoToneStrength=+e.target.value;$('#alphaLock').onchange=e=>state.alphaLock=e.target.checked;$('#fillMode').onchange=e=>state.fillMode=e.target.value;$('#replaceScope').onchange=e=>state.replaceScope=e.target.value;
 $('#colorHex').addEventListener('change',e=>setColor(e.target.value));bindColorPad();
 $('#partMirror').onchange=e=>state.partMirror=e.target.checked;$('#axisMirror').onchange=e=>state.axisMirror=e.target.checked;
 $('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;$('#selectionCopyBtn').onclick=copySelection;$('#selectionPasteBtn').onclick=pasteSelection;$('#selectionFlipHBtn').onclick=()=>flipSelection(true);$('#selectionFlipVBtn').onclick=()=>flipSelection(false);$('#selectionDeleteBtn').onclick=deleteSelection;$('#selectionClearBtn').onclick=clearSelection;
 $('#addLayerBtn').onclick=addLayer;$('#duplicateLayerBtn').onclick=duplicateLayer;$('#deleteLayerBtn').onclick=deleteLayer;$('#moveLayerUpBtn').onclick=()=>moveLayer(1);$('#moveLayerDownBtn').onclick=()=>moveLayer(-1);$('#mergeDownBtn').onclick=mergeDown;
 $('#bodyModeBtn').onclick=()=>{state.skin.surface='body';updateSkinVisibility()};$('#outerModeBtn').onclick=()=>{state.skin.surface='outer';updateSkinVisibility()};$('#gridBtn').onclick=()=>{state.skin.grid=!state.skin.grid;$('#gridBtn').classList.toggle('active',state.skin.grid);$('#viewport').classList.toggle('grid-on',state.skin.grid);setStatus(state.skin.grid?'グリッド ON':'グリッド OFF')};$('#resetViewBtn').onclick=()=>{Object.assign(state.skin.view,{rx:-10,ry:28,zoom:1,panX:0,panY:0});updateSkinView()};$('#toggleUVBtn').onclick=()=>$('#uvPanel').classList.toggle('hidden');$('#closeUVBtn').onclick=()=>$('#uvPanel').classList.add('hidden');
 $$('.part-toggle').forEach(b=>b.onclick=()=>{state.skin.partVisibility[b.dataset.part]=!state.skin.partVisibility[b.dataset.part];b.classList.toggle('active',state.skin.partVisibility[b.dataset.part]);updateSkinVisibility()});$('#showBody').onchange=e=>{state.skin.showBody=e.target.checked;updateSkinVisibility()};$('#showOuter').onchange=e=>{state.skin.showOuter=e.target.checked;updateSkinVisibility()};$('#armModel').onchange=e=>{state.skin.armModel=e.target.value;buildSkinModel()};
 $('#compareOpacity').addEventListener('input',e=>{state.skin.compareOpacity=+e.target.value/100;$('#compareOpacityLabel').textContent=e.target.value+'%';refreshSkin()});$('#compareVisible').onchange=e=>{state.skin.compareVisible=e.target.checked;refreshSkin()};$('#loadCompareBtn').onclick=()=>$('#compareFileInput').click();$('#clearCompareBtn').onclick=()=>{state.skin.compare=null;refreshSkin()};
 $('#skinNewBtn').onclick=()=>{if(confirm('Skinを新規作成しますか？')){state.skin.layers=[makeLayer('Base',64,64)];state.skin.activeLayer=0;state.skin.compare=null;buildSkinModel();renderLayers();resetHistory()}};$('#skinOpenBtn').onclick=()=>$('#skinFileInput').click();$('#skinPreviewBtn').onclick=()=>{buildSkinPreviewModel();$('#skinPreview').classList.remove('hidden');updateSkinPreviewView()};$('#closeSkinPreviewBtn').onclick=()=>$('#skinPreview').classList.add('hidden');$('#resetSkinPreviewBtn').onclick=()=>{Object.assign(state.skin.previewView,{rx:0,ry:0,zoom:1,panX:0,panY:0});updateSkinPreviewView()};$('#skinExportBtn').onclick=exportSkin;$('#skinProjectSaveBtn').onclick=saveSkinProject;$('#skinProjectOpenBtn').onclick=()=>$('#skinProjectInput').click();
 $('#skinFileInput').onchange=e=>e.target.files[0]&&importSkinPNG(e.target.files[0]);$('#compareFileInput').onchange=e=>e.target.files[0]&&importSkinPNG(e.target.files[0],true);$('#skinProjectInput').onchange=e=>e.target.files[0]&&loadSkinProject(e.target.files[0]).catch(err=>alert(err.message));
 $('#bbOpenBtn').onclick=()=>$('#bbFileInput').click();$('#bbFileInput').onchange=e=>e.target.files[0]&&loadBBModel(e.target.files[0]);$('#modelTextureOpenBtn').onclick=()=>$('#modelTextureInput').click();$('#modelTextureInput').onchange=e=>e.target.files[0]&&importModelTexture(e.target.files[0]);$('#modelTextureExportBtn').onclick=exportModelTexture;$('#modelMcmetaExportBtn').onclick=()=>exportMcmeta('model');$('#modelGrid').onchange=e=>{state.model.grid=e.target.checked;$('#modelViewport').classList.toggle('grid-on',state.model.grid)};$('#modelResetViewBtn').onclick=()=>{Object.assign(state.model.view,{rx:-12,ry:30,zoom:1,panX:0,panY:0});updateModelView()};
 $('#modelPrevFrame').onclick=()=>stepFrame('model',-1);$('#modelNextFrame').onclick=()=>stepFrame('model',1);$('#modelAddFrame').onclick=()=>addFrame('model',false);$('#modelDupFrame').onclick=()=>addFrame('model',true);$('#modelDelFrame').onclick=()=>delFrame('model');$('#modelPlayBtn').onclick=()=>togglePlay('model');$('#modelFps').onchange=e=>{state.model.fps=+e.target.value;if(state.model.playing){togglePlay('model');togglePlay('model')}};
 $('#itemSize').onchange=e=>changeItemSize(e.target.value);$('#itemNewBtn').onclick=newItem;$('#itemOpenBtn').onclick=()=>$('#itemFileInput').click();$('#itemFileInput').onchange=e=>e.target.files[0]&&importAnimatedPNG(e.target.files[0],'item');$('#itemExportBtn').onclick=()=>exportAnimatedPNG('item');$('#itemMcmetaBtn').onclick=()=>exportMcmeta('item');$('#itemPrevFrame').onclick=()=>stepFrame('item',-1);$('#itemNextFrame').onclick=()=>stepFrame('item',1);$('#itemAddFrame').onclick=()=>addFrame('item',false);$('#itemDupFrame').onclick=()=>addFrame('item',true);$('#itemDelFrame').onclick=()=>delFrame('item');$('#itemPlayBtn').onclick=()=>togglePlay('item');$('#itemFps').onchange=e=>{state.item.fps=+e.target.value;if(state.item.playing){togglePlay('item');togglePlay('item')}};
 $('#blockSize').onchange=e=>changeBlockSize(e.target.value);$('#blockNewBtn').onclick=newBlock;$('#blockOpenBtn').onclick=()=>$('#blockFileInput').click();$('#blockFileInput').onchange=e=>e.target.files[0]&&importAnimatedPNG(e.target.files[0],'block');$('#blockExportBtn').onclick=()=>exportAnimatedPNG('block');$('#blockMcmetaBtn').onclick=()=>exportMcmeta('block');$('#blockPrevFrame').onclick=()=>stepFrame('block',-1);$('#blockNextFrame').onclick=()=>stepFrame('block',1);$('#blockAddFrame').onclick=()=>addFrame('block',false);$('#blockDupFrame').onclick=()=>addFrame('block',true);$('#blockDelFrame').onclick=()=>delFrame('block');$('#blockPlayBtn').onclick=()=>togglePlay('block');$('#blockFps').onchange=e=>{state.block.fps=+e.target.value;if(state.block.playing){togglePlay('block');togglePlay('block')}};$('#blockResetViewBtn').onclick=()=>{Object.assign(state.block.view,{rx:-18,ry:32,zoom:1,panX:0,panY:0});updateBlockView()};
 bindUVCanvas();bindPixelCanvas($('#itemCanvas'),'item');bindPixelCanvas($('#blockCanvas'),'block');setupViewport($('#viewport'),state.skin.view,updateSkinView);setupViewport($('#modelViewport'),state.model.view,updateModelView);setupViewport($('#skinPreview'),state.skin.previewView,updateSkinPreviewView);setupViewport($('#blockPreviewScene'),state.block.view,updateBlockView);
 document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;const k=e.key.toLowerCase();if((e.ctrlKey||e.metaKey)&&k==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if((e.ctrlKey||e.metaKey)&&k==='y'){e.preventDefault();redo()}else if((e.ctrlKey||e.metaKey)&&k==='c'&&selectionMatchesCurrent()){e.preventDefault();copySelection()}else if((e.ctrlKey||e.metaKey)&&k==='v'&&state.selectionClipboard){e.preventDefault();pasteSelection()}else if(k==='delete'&&selectionMatchesCurrent()){e.preventDefault();deleteSelection()}else if(k==='b')setTool('brush');else if(k==='e')setTool('eraser');else if(k==='g')setTool('fill');else if(k==='i')setTool('eyedropper')});
}
function setTool(t){const b=$(`.tool[data-tool="${t}"]`);b?.click()}
function bindUVCanvas(){const c=$('#uvCanvas');let down=false;c.addEventListener('pointerdown',e=>{if(e.button!==0)return;down=true;pushUndo();paintUV(e)});c.addEventListener('pointermove',e=>down&&paintUV(e));c.addEventListener('pointerup',()=>{down=false;markChanged('UV編集')});c.addEventListener('pointercancel',()=>down=false)}
function paintUV(e){const c=$('#uvCanvas'),r=c.getBoundingClientRect(),x=clamp(Math.floor((e.clientX-r.left)/r.width*64),0,63),y=clamp(Math.floor((e.clientY-r.top)/r.height*64),0,63),l=state.skin.layers[state.skin.activeLayer];if(state.tool==='eyedropper'||e.altKey){sampleAt(l.ctx,x,y);return}if(state.tool==='fill'){floodFill(l.ctx,x,y,e.shiftKey);refreshSkin();return}const erase=state.tool==='eraser'||e.shiftKey;for(const [dx,dy] of brushOffsets(state.brushSize,state.brushShape))putPixel(l.ctx,x+dx,y+dy,64,64,erase);refreshSkin()}
